[build]
command = "npm run build"
publish = "dist"

[functions]
directory = "netlify/functions"

[[redirects]]
from = "/api/auth/login_otp"
to = "/.netlify/functions/auth"
status = 200

[[redirects]]
from = "/api/rc/rc_verify"
to = "/.netlify/functions/rc"
status = 200

[[redirects]]
from = "/api/auth/verify_otp"
to = "/.netlify/functions/verify-otp"
status = 200